### ISSUE TITLE
Criar atributo para exibir pontos facultativos de forma distinta

### ISSUE THREAD

**Issue by lpanebr** [alexandrehtrb/FeriadosDoBrasil#2]

**Comment by alexandrehtrb** [comment]
Feito como marcação de emendas de feriados

**Comment by lpanebr** [comment]
Que interessante marcar as emendas! Gostei!

Eu tinha imaginado diferenciar a cor de feriados que em alguns municípios são opcionais mesmo. Não tenho como pegar exemplo agora.
